M48
; DRILL file {KiCad 8.0.8} date 2025-02-21T17:49:05-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-21T17:49:05-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X1.1614Y-0.8661
X1.8167Y-3.8386
X4.0061Y-3.8386
X4.7638Y-4.4291
M30
